asian_decoration/asian_decoration/urls.py
from django.contrib import admin
from django.urls import path ,include
from django.conf import settings
from django.conf.urls import url
from  django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dec_app.urls')),
    path('carts/', include('cart_app.urls')),
    path('checkout/', include('order.urls')),
    path('account/', include('accounts.urls')),

]

urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

asian_decoration/carts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.view_ca, name='carts_det'),
    path('Add_to_cart/<slug>', views.add_to_cart, name='pro_add_to_cart'),
]

asian_decoration/cart_app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
from dec_app.models import rel_pro


class carts(models.Model):
    # items = models.ManyToManyField(CartItem, null=True, blank=True)
    # rel_pros = models.ManyToManyField(rel_pro, null=True, blank=True)
    total = models.DecimalField(decimal_places=2, max_digits=100, default=0.00)
    available = models.BooleanField(default=True)


class CartItem(models.Model):
    cart = models.ForeignKey(carts, null=True, blank=True, on_delete=models.CASCADE)
    product = models.ForeignKey(rel_pro, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    line_total = models.DecimalField(default=10.99, max_digits=1000, decimal_places=2)

    def __unicode__(self):
        try:
            return str(self.cart.id)
        except:
            return  self.product.name

asian_decoration/carts/models.py
from django.db import models
from dec_app.models import rel_pro


# import model of product


# foreign key of carts

class cart_item(models.Model):
    Product = models.ForeignKey(rel_pro, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)


class carts(models.Model):
    items = models.ManyToManyField(cart_item, null=True, blank=True)
    rel_pros = models.ManyToManyField(rel_pro, null=True, blank=True)
    total = models.DecimalField(max_length=100, decimal_places=2, max_digits=5, default=0.00)
    available = models.BooleanField(default=True)

asian_decoration/carts/views.py
from django.shortcuts import render, HttpResponseRedirect, get_object_or_404, get_list_or_404
from django.urls import reverse
# Create your views here.
from .models import carts, cart_item
from dec_app.models import rel_pro


def view_ca(request):
    try:
        the_id = request.session['carts_id']
    except:
        the_id = None
    if the_id:
        carts1 = carts.objects.get(id=the_id)
        context = {'carts1': carts1}
    else:
        empty_message = "your cart is empty"
        context = {'carts1': True, "empty_message": empty_message}
    templates = 'cart/cart_view.html'
    return render(request, templates, context)


def add_to_cart(request, slug):
    request.session.set_expiry(120000)
    try:
        # aleredy exist person
        the_id = request.session['carts_id']
        print(the_id)
    except:
        # create new id and session
        new_cart = carts()
        new_cart.save()
        request.session['carts_id'] = new_cart.id
        the_id = new_cart.id

    carts1 = carts.objects.get(id=the_id)
    print("1", carts1)
    try:
        # get_obj_or_404(where you want to get , what get) mthod get only one object
        # Product = rel_pro.objects.get(slug=slug)  or
        Product = get_object_or_404(rel_pro, slug=slug)
        print("2", Product)
    except Product.DoesNotExist:
        pass
    except:
        pass
    # below code creating cart item for us
    # it returns ("model object", "true/false")
    Cart_item, created = cart_item.objects.get_or_create(Product=Product)
    if created:
        print("created")
    # end
    if not Cart_item in carts1.items.all():
        # adding product into  the cart
        carts1.items.add(Cart_item)
        print("3", carts1)
    else:
        # remove product into cart
        carts1.items.remove(Cart_item)
        print("4", carts1)

    # cart all item total
    new_total = 0.00
    for itm in carts1.items.all():
        line_total = float(itm.Product.price) * round(itm.quantity, 2)
        print(line_total)
        new_total += line_total
        print(new_total)

    # count the total number of itm in cart
    request.session['item_total'] = carts1.items.all().count()
    print(carts1.rel_pros.all().count())
    carts1.total = new_total
    carts1.save()

    return HttpResponseRedirect(reverse("carts_det"))

asian_decoration/templates/cart/cart_view.html
{% extends 'base.html' %} <!-- inherite base.html file at first line of page -->
{% load static %}
  
  {% block title %} <title>: : Cart : :</title> {% endblock %} 
  

  {% block body %}

  {% if empty_message %}
      <h1>{{ empty_message }}</h1>
      <script>alert("{{ empty_message }}")</script>
  {% else %}
        	<div class="container_cate" style="margin-left: 40px;">
            <div id="heading-block" style="color: gold">
                <h2 style="color: white; background-color: black; margin:12px;">CART DETAIL'S</h2><hr/>
            </div>
          </div>
          <div class="cart_container" style="margin-left:50px;margin-top: 10%;">
            <div>
              <P></P>
            </div>
            <table class="content-table" style="color: #fff;">
              <thead>
                <tr>
                  <th>Product Images</th>
                  <th>Product Name</th>
                  <th>Unit Price</th>
                  <th>Qty</th>
                  <th>Update Quantity</th>
                </tr>
              </thead>
              <tbody>
              {% for item in cart.cartitem_set.all %}
                <tr>
                  <td ><img src="{{ item.product.image.url }}" alt="image1" width="100px" height="100px" style="padding:5px;"></td>
                  <td>{{ item.product.name }}</td>
                  <td>Rs.{{ item.product.price }}</td>
                  <td>{{ item.quantity }}</td>
                  <td>
                  <form  method="get" action='{% url "pro_add_to_cart" item.product.slug  %}'>
                      <input type="number" min="0" name="qty" style="width: 35px; height: 20px; color:black; " />
                      <input type="submit" value="  Add  ">
                  </form>
                  </td>
                  <td><a href='{% url "pro_add_to_cart" item.product.slug  %}?qty=0'><span style="background-color:red; padding: 5px 5px 5px 5px;height: 10px;color: #fff;"><i class="fa fa-trash-o" >&nbsp;Remove</i></span></a></td>
                </tr>
              {% endfor %}
              <tfoot>
                <tr>
                  <th>Sub Total</th>
                  <th></th>
                  <th></th>
                  <th></th>
                  <th>Rs.{{ cart.total }}</th>
                </tr>
                <tr>
                  <th>Tax</th>
                  <th></th>
                  <th></th>
                  <th></th>
                  <th>Rs.0.00</th>
                </tr>
                <tr>
                  <th>Shipping Charges</th>
                  <th></th>
                  <th></th>
                  <th style="border-bottom: 2px solid gold;"></th>
                  <th style="border-bottom: 2px solid gold;">Rs.0.00</th>
                </tr>
                <tr>
                  <th></th>
                  <th></th>
                  <th></th>
                  <th>Total Amount: </th>
                  <th>Rs.{{ cart.total }}</th>
                </tr>
              </tfoot>
            </table>
              <div class="cart_btn_left_right">
                <div class="left" style="float: left;margin-left: 150px;">
                  <a href="/" ><button style="background: gold;color: #ffffff;width: 170px;font-weight: bold;font-size: 15px;height: 40px;border:none;cursor: pointer;border-radius: 10px;" class="btn btn-outline-secondary"><i class="fa fa-chevron-left"></i> Continue Shopping</button></a>
                </div>
                <div class="right" style="float: right;margin-right: 210px;">
                    <a href="#" style="padding-right: 15px;"><button style="background: gold;color: #ffffff;width: 170px;font-weight: bold;font-size: 15px;height: 40px;border:none;border-radius: 10px;cursor: pointer;" class="btn btn-outline-secondary"><i class="fa fa-refresh"></i> Update cart</button></a>
                    <a href='{% url "order_info" %}'><button type="submit" class="btn btn-primary" style="background: #0D872D;font-size: 20px;box-shadow: 0 0 10px gold;border: none;border-radius: 10px;font-weight: bolder;width: 230px;height: 50px;cursor: pointer;color: #fff;">
                      Proceed to checkout <i class="fa fa-chevron-right"></i></button></a>
                </div>
              </div>
          </div>
          </div>
            {% endif %}
 {% endblock %}